name: verlan
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pip:
      - torch==2.2.2+cu118 --index-url https://download.pytorch.org/whl/cu118
      - transformers==4.40.2
      - datasets==2.19.0
      - peft==0.11.1
      - trl==0.8.6
      - bitsandbytes==0.43.1
      - pandas==2.2.2
      - numpy==1.26.4
      - scikit-learn==1.4.2
      - joblib==1.4.0
      - openpyxl==3.1.2
